### ISSUE TITLE
Boring and stable libraries

### ISSUE THREAD

**Issue by gr0uch** [yoshuawuyts/the-tiny-guide-to-non-fancy-node#6]
I agree with most of this guide except this part sounds too idealistic.

How can libraries that are barely a year old and have gone through multiple major versions with presumably breaking changes already be "boring and stable"?

Not even Node.js itself is boring and stable, it's gone through lots of churn over the few years of its existence, so you're not safe by sticking with the core modules, just relatively safer.

The only way for something to actually be boring and stable is to never make breaking changes, i.e. never release a major version past 1.0. This means that the interface must be frozen and unversioned.

**Comment by yoshuawuyts** [comment]
Stability means getting things right; both in terms of scoping and implementation. I think `browserify` is a shining example of getting things right. It took more than one iteration to get the API working, but now that it does only some of the underlying components need to be updated - e.g. stuff like the `acorn` parser. But `browserify` itself remains stable. The latest breaking change was [13.0.0](https://github.com/substack/node-browserify/blob/master/changelog.markdown#1300) because a dependency had changes its API which could cause an issue in an extremely rare edge case. No actual changes were made to the package.

Another example is `leveldown`. It's depended upon by a large set of packages, but is extremely reliable. If you look at [the commit history](https://github.com/Level/levelup/commits/master) the latest actual change was in May last year to make sure binaries work if C++ 11 is not present. The change before that is from November 2015 to "track and expose chained batch ops queue length". Everything else has pretty much been dependency bumps and docs fixes.

The point you highlight about Node.js is correct: Node _is_ changing. Not everyone is content with the current direction of Node, both inside and outside core development. If you're interested in the topic, I recommend reading [stability first](http://mafintosh.com/stability-first.html) by my co-worker  Mafintosh.

I think in the end stability is about keeping APIs stable, and fixing bugs. If you're in complete vertical control of dependencies and / or have a stable platform it's actually possible to have stable code. The packages and techniques I highlight in the guide are exactly this: they're stable, which means if you rely on them you inherit this stability in your code. I think showing people this was my goal in writing this guide.

Anyway, I hope this answers your question and quells your skepticism a little. This repository is not about abstract theory crafting, but actual field notes coming from the trenches of years of Node development. I hope it'll be of use to you (:

**Comment by gr0uch** [comment]
Thanks for the well-thought response.

>If you're in complete vertical control of dependencies and / or have a stable platform

I don't think this is feasible in software development in general. Not many people are going to write their own HTTP implementation because Node.js / libuv don't do a good enough job at it. To quote Ryan Dahl:

>Those of us who build on top of these systems are adding to the complexity. 

On a related note, salaried programmers don't seem to get paid for stability, often they are paid to fix their own bugs. If the bugs disappeared, some programmers would be out of a job.

**Comment by sotojuan** [comment]
Salaried programmers are rushed by their managers and market needs so they don't have time to care about stability. Also, a lot of programmers change jobs every 2-4 years so the technical debt doesn't matter to them. In those 2-4 years, it "pays" to use the latest and trendiest to make your resume more attractive. The result of all of this is unstable, poorly thought-out, dependency-crazy software.
