### ISSUE TITLE
How to test for the browser?

### ISSUE THREAD

**Issue by YerkoPalma** [yoshuawuyts/the-tiny-guide-to-non-fancy-node#7]
Hi, nice guide, thanks for sharing it. 
Now, I was wondering, how do you do to test the browser? In the testing section you mention tape, for the unit testing, in node it is pretty straight forward, but I always have problems to test in the browser, so, I want to ask, how do you test the browser? Using some dom mimic library like jsdom or browser-env? or something more complex like a headless browser, e.g. phantomjs? What would be your recomendation?

Thanks again for the guide ;)

**Comment by derhuerst** [comment]
I know this is a repo which reflects the personal opinion of @yoshuawuyts. But since he's pretty busy, I'll point out a few things which I think he will agree with.

---

**If you write all of your code as tiny modules, many of the use cases** for end-to-end testing, integration testing & browser testing (or whatever you might call it) **actually disappear.**

As an example: If your module `foo` will just render some DOM tree, it can (and @yoshuawuyts's modules often do) rely on e.g. [`yo-yo`](https://github.com/maxogden/yo-yo#readme) to create & diff DOM elements from template strings. Therefore, you can test `foo` by either inspecting the returned DOM tree outside of a browser, or by even mocking `yo-yo` and making sure it gets called with the right values.

---

**For modules which directly depend on browser APIs**, where the quirks of the latter are relevant, (e.g. polyfills/ponyfills), **actual browser testing is useful**, as it wouldn't make sense to mock all those quirks and edge cases you face in browsers. Imagine the audio api as an example for this. I am interested in @yoshuawuyts's position on this.

**Comment by yoshuawuyts** [comment]
Yup, agree

**Comment by yoshuawuyts** [comment]
Think this question is answered now - closing! :sparkles:

oh ps you might wanna check out https://github.com/juliangruber/tape-run - it's neat for unit testing in a browser env (:

**Comment by YerkoPalma** [comment]
Nice module, I'll check it later. Thanks for the hint.
